import { StyleSheet, Dimensions, I18nManager } from 'react-native';
const { width, height } = Dimensions.get('screen');
// const ffamilybold = I18nManager.isRTL ? 'IRANSANS' : 'TwCenMT-Bold';
// const ffamily = I18nManager.isRTL ? 'IRANSANS' : 'TwCenMT-Regular';
const fontsizes =
  width < 680 ? [9, 12, 14, 16, 18, 20] : [9, 14, 16, 18, 20, 24];
const IconSize =
  width < 680 ? [34, 32, 30, 28, 26, 18] : [36, 34, 32, 30, 28, 2];
export default StyleSheet.create({
  facultylist: {
    fontSize: fontsizes[4],
    fontFamily: 'IRANSans-Bold',
    color: '#413d3a',
    marginHorizontal: 20,
    marginTop: 10,
    marginBottom: 10,
  },
  profileimg: {
    marginBottom: 15,
    paddingLeft: 15,
    flexDirection: 'row',
    backgroundColor: '#FFFF',
    // justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 5,
    // backgroundColor: 'red',
  },
  facultyaddnum: {
    backgroundColor: '#2F9FD5',
    // marginHorizontal: 3,
    marginRight: 15,
    justifyContent: 'center',
    alignItems: 'center',
    width: width * 0.1,
    height: width * 0.1,
    borderRadius: width * 0.05,
  },
  txtnum: {
    fontSize: fontsizes[1],
    fontFamily: 'IRANSANS',
    color: '#FFFF',
  },
  headermainscr: {
    alignSelf: 'center',
    height: height * 0.2,
    width: (width * 95) / 100,
    borderBottomLeftRadius: (width * 5) / 100,
    borderBottomRightRadius: (width * 5) / 100,
    borderTopRightRadius: (width * 5) / 100,
    borderTopLeftRadius: (width * 5) / 100,
    overflow: 'hidden',
    backgroundColor: '#eaeef7',
    zIndex: 1,
    marginRight: 5
  },
  linearimg: {
    height: '100%',
    width: '100%',
    position: 'absolute',
    top: 0,
    zIndex: 2,
    flexDirection: 'row-reverse',
  },
  upcomingtouch: {
    position: 'absolute',
    top: 0,
    right: 0,
    zIndex: 2,
    flexDirection: 'row',
    marginTop: 20,
    marginRight: 15,
    // alignItems: 'baseline',
    borderWidth: 2,
    borderRadius: 20,
    borderColor: '#7988FF',
    backgroundColor: '#FFFF',
    width: '25%',
    height: '11%',
  },
  upcomingtxt: {
    fontFamily: 'IRANSANS',
    fontSize: fontsizes[0],
    padding: 0,
    width: '100%',
    textAlign: 'center'
  },
  likeAndShare: {
    position: 'absolute',
    width: (width * 35) / 100,
    height: (width * 8) / 100,
    bottom: 25,
    right: 5,
  },
  likeAndShareViewIcon: {
    flexDirection: 'row',
    padding: 5,
    display: 'flex',
    justifyContent: 'space-around',
  },
  likeAndShareIcon: {
    width: (width * 7.9) / 100,
    height: (width * 7.9) / 100,
    fontSize: IconSize[5],
    backgroundColor: '#808080',
    borderRadius: 100,
    padding: 6
  },
  btnlogoview: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FFFF',
    zIndex: 4,
    // paddingVertical: 10,
  },
  btnbottomview: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginRight: 15,
  },
  imglogo: {
    width: 80,
    height: 80,
    marginTop: -40,
    marginLeft: 15,
    borderColor: '#FFFF',
    borderWidth: 4,
    borderRadius: 5,
  },
  btnaddcalendar: {
    borderColor: '#4D63FF',
    borderWidth: 2,
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 20,
  },
  txtaddcalendar: {
    color: '#4D63FF',
    fontFamily: 'IRANSANS',
    fontSize: fontsizes[0],
  },
  dateRateview: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  details: {
    backgroundColor: '#FFFF',
    height: (width * 30) / 100,
    marginTop: 0,
    borderTopRightRadius: (width * 4) / 100,
    borderTopLeftRadius: (width * 4) / 100,
    zIndex: 3
  },
  detailsDateAndLocation: {
    flexDirection: 'column',
    width: '70%',
    paddingTop: 5,
  },
  titleview: {
    paddingTop: 10,
  },
  titletxt: {
    marginLeft:15 ,
    fontFamily: 'IRANSANS',
    fontSize: fontsizes[3],
    fontWeight: 'bold',
  },
  dateview: {
    flexDirection: 'row',
    alignItems:'center',
    marginLeft: 20,
    justifyContent:'flex-start',
    paddingTop: 4
  },
  datetxt: {

    
    color: '#8A8A8A',
    fontFamily: 'IRANSANS',
    fontSize: fontsizes[1],
  },
  websiteview: {
    marginRight: 50,
    alignItems: 'center',
    // backgroundColor: 'red',
    height: '100%',
    width: '100%'
  },
  websitetxt: {
    color: '#1C00FE',
    fontFamily: 'IRANSANS',
    fontSize: fontsizes[1],
  },
  mainview: {
    backgroundColor: '#FAFAFA',
     height:( height * 52) / 100,
     //width: (width * 40) / 100,
    
  },
  mainviewCount: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 20,
    marginTop: 10,
    paddingHorizontal: 5,
    height: '100%',
    width: '55%'
  },
  countview: {
    alignItems: 'center',
    color: '#464646',
    marginBottom: 5,
  },
  counttxt: {
    fontFamily: 'IRANSANS',
    fontSize: fontsizes[5],
    fontWeight: 'bold',
  },
  countDaytxt: {
    fontFamily: 'IRANSANS',
    fontSize: fontsizes[0],
  },
  texttxt: {
    fontFamily: 'IRANSANS',
    fontSize: fontsizes[2],
    color: '#575757',
    margin: 20,
  },
  btnview: {
    width: width,
    alignItems:'center',
    height: (width * 15) / 100,
    backgroundColor: '#FFFF',
    position: 'absolute',
    bottom: 0,
    zIndex: 6,
    flexDirection: 'row',
    // justifyContent: 'space-around',
  },
  btnTouchview: {
    backgroundColor: '#003056',
    marginVertical: (width * 3) / 100,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 5,
    height:(width * 9) / 100,
  },
  btnTouchtxt: {
    color: '#FFFF',
    fontFamily: 'IRANSANS',
    fontSize: fontsizes[2],
  },
  ModalBackBlure: {
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
    width: '100%',
    height: '100%',
    top: 0,
    right: 0,
    alignSelf: 'center',
    backgroundColor: 'black',
    opacity: 0.5,
    // zIndex: 50,
  },
  ModalWith: {
    padding: 20,
    width: '90%',
    alignItems: 'center',
    justifyContent: 'center',
    // borderRadius: 20,
    backgroundColor: '#FFFF',
  },
  ModalBack: {
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
    zIndex: 70,
    width: '100%',
    height: '100%',
    alignSelf: 'center',
    // zIndex: 52,
    // backgroundColor: 'red',
    // opacity: .5
  },
  madalRezvpinfo: {
    width: 30,
    height: 30,
    // transform: [{ rotate: '90deg' }],
    justifyContent: 'center',
    // alignItems: 'center',
    top: 35,
    left: -150,
    // position: 'absolute',
    zIndex: 72,
    // backgroundColor: 'red',
  },
  modalvpinfo: {
    width: 30,
    height: 30,
    // top: 20, right: 20,
    // top: 25,
    borderRadius: 15,
    marginTop: 15,
    backgroundColor: 'gray',
    position: 'absolute',
    opacity: 0.5,
    alignSelf: 'center',
  },
  modalipinfo: {
    color: '#FFFF',
    fontFamily: 'IRANSANS',
    fontSize: fontsizes[3],
    opacity: 2,
    alignSelf: 'center',
  },
  moadalimg: {
    width: 60,
    height: 40,
  },
  emailinp: {
    borderBottomColor: '#C1C1C1',
    borderBottomWidth: 1,
    width: '90%',
    paddingVertical: 10,
  },
  continuebtn: {
    backgroundColor: '#7992A6',
    width: width * 0.5,
    alignItems: 'center',
    paddingVertical: 10,
    marginTop: 15,
    marginBottom: 50,
  },
  continuetxt: {
    color: '#FFFF',
    fontFamily: 'IRANSANS',
    fontSize: fontsizes[1],
  },
  mpltxt: {
    textAlign: 'justify',
    fontFamily: 'IRANSANS',
    fontSize: fontsizes[2],
    fontWeight: 'bold',
    marginVertical: 3,
  },
  imgbackheader: {
    height: '100%',
    width: '100%',
    // borderBottomLeftRadius: (width * 10) / 100,
    // borderBottomRightRadius: (width * 10) / 100,
    // overflow: 'hidden',
  },
  mapviews: {
    height: height * 0.3,
    marginHorizontal: 20,
    backgroundColor: '#FFFF',
  },
  maptxt: {
    marginVertical: 15,
  },
  calendaricon: {
    color: 'grey',
    fontSize: IconSize[5],
  },
  textinputlogin: {
    width: '90%',
    // backgroundColor: 'red',
    paddingVertical: 12,
    paddingLeft: 5,
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
    color: 'grey',
    borderBottomColor: 'grey',
    borderBottomWidth: 1,
    // overflow: 'hidden',
    // ...Platform.select({
    //   ios: {
    //     shadowColor: '#000',
    //     shadowOffset: {
    //       width: 1,
    //       height: 1,
    //     },
    //     shadowOpacity: 0.22,
    //     shadowRadius: 0.22,
    //   },
    //   android: {
    //     elevation: 1,
    //   },
    // }),
  },
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 70,
  },
  activityIndicator: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    height: 80,
  },
  addmycalendartxt: {
    color: '#5163FF',
    fontFamily: 'IRANSANS',
    fontSize: fontsizes[1],
    borderWidth: 1,
    borderColor: '#5163FF',
    borderRadius: 15,
    paddingVertical: 3,
    paddingHorizontal: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  about: {
    flexDirection: 'column',
  },
  aboutText: {
    fontSize: fontsizes[5],
    fontWeight: '800'
  },
  line: {
    flex: 1, height: 1, backgroundColor: 'black'
  },
  aboutTextFull: {
    minHeight: (width * 85) / 100,
    maxHeight: (width * 85) / 100,
  },
  facultylist: {
    fontSize: fontsizes[4],
    fontFamily: 'IRANSans-Bold',
    color: '#413d3a',
    marginHorizontal: 20,
    marginTop: 10,
    marginBottom: 10,
  },
  facultypersonv: {
    backgroundColor: '#eaeaea',
    marginHorizontal: 3,
    justifyContent: 'center',
    alignItems: 'center',
    width: width * 0.1,
    height: width * 0.1,
    borderRadius: width * 0.1,
    overflow: 'hidden',
  },
  facultyaddnum: {
    backgroundColor: '#2F9FD5',
    // marginHorizontal: 3,
    marginRight: 15,
    justifyContent: 'center',
    alignItems: 'center',
    width: width * 0.1,
    height: width * 0.1,
    borderRadius: width * 0.05,
  },
  facultypersonimg: {
    width: '100%',
    height: '100%',
  },
  lineGery: {
    display: 'flex',
    height: 2,
    borderRadius: 50,
    backgroundColor: '#E0E0E0',
    width: '95%',
    marginVertical: 5,
    alignSelf:'center'
  }
});
