import {StyleSheet, Dimensions, I18nManager} from 'react-native';
const {width, height} = Dimensions.get('screen');
// const ffamilybold = I18nManager.isRTL ? 'IRANSANS' : 'TwCenMT-Bold';
// const ffamily = I18nManager.isRTL ? 'IRANSANS' : 'TwCenMT-Regular';
const fontsizes =
  width < 680 ? [9, 12, 14, 16, 18, 20] : [9, 14, 16, 18, 20, 24];
const IconSize = width < 680 ? [34, 32, 30, 28, 26] : [36, 34, 32, 30, 28];
export default StyleSheet.create({
  mainscrview: {
    backgroundColor: '#f0f4fd',
    height,
  },
  arrowimg: {
    height: height * 0.02,
    width: width * 0.03,
  },
  animindex: {
    position: 'absolute',
    zIndex: 5,
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: '#DB2227',
    overflow: 'hidden',
  },
  headermainscr: {
    height: height * 0.4,
    borderBottomLeftRadius: (width * 10) / 100,
    borderBottomRightRadius: (width * 10) / 100,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    // backgroundColor: 'green',
    // paddingBottom: 5,
    marginBottom: 15,
  },
  imgbackheader: {
    // backgroundColor: 'red',
    width: (width * 100) / 100,
    height: '100%',
    borderBottomLeftRadius: (width * 10) / 100,
    borderBottomRightRadius: (width * 10) / 100,

    // marginBottom: 25,
    overflow: 'hidden',
  },
  imglinear: {
    width: (width * 100) / 100,
    height: '100%',
    borderBottomLeftRadius: (width * 5) / 100,
    borderBottomRightRadius: (width * 5) / 100,
    // overflow: 'hidden',
    // position: 'absolute',
    // zIndex: 2,
    opacity: 0.6,
  },
  txtbookm: {
    fontSize: fontsizes[3],
    fontFamily: 'IRANSans-Bold',
    color: '#bababa',
  },
  bookview: {
    flexDirection: 'column',
    backgroundColor: '#FFFF',
    alignSelf: 'center',
    paddingVertical: 10,
    paddingHorizontal: 5,
    borderRadius: 10,
    top: height * 0.33,
    position: 'absolute',
    zIndex: 2,
  },
  writenoteview: {
    paddingHorizontal: 15,
    alignItems: 'center',
  },
  imgexhabitnote: {
    width: width * 0.05,
    height: height * 0.04,
    borderRadius: 5,
    // marginHorizontal: 10,
  },
  txtimg: {
    fontSize: fontsizes[1],
    fontFamily: 'IRANSANS',
  },
  viewnamedetail: {
    marginTop: 15,
    backgroundColor: '#FFFF',
    alignItems: 'center',
    paddingVertical: 15,
  },
  namedetail: {
    fontSize: fontsizes[5],
    fontFamily: 'IRANSans-Bold',
    color: 'grey',
  },
  namedetail2: {
    fontSize: fontsizes[4],
    fontFamily: 'IRANSans-Bold',
    color: 'black',
  },
  //   viewnamedetail: {
  //     marginTop: height * 0.02,
  //     backgroundColor: '#FFFF',
  //     flexDirection: 'column',
  //     // justifyContent: 'center',
  //     alignItems: 'center',
  //     paddingVertical: 5,
  //   },
  bottcarevents: {
    flexDirection: 'row',
    padding: 5,
    // backgroundColor: 'red',
    // justifyContent: 'space-between',
  },
  reeventbott: {
    flexDirection: 'row',
    paddingHorizontal: 10,
    alignItems: 'center',
  },
  imgbottcarevents: {
    width: width * 0.07,
    height: height * 0.04,
    marginRight: 10,
  },
  txtcareventdate: {
    fontFamily: 'IRANSans-Bold',
    fontSize: fontsizes[1],
    color: '#a6aaab',
  },
  addevedate: {
    flexDirection: 'row',
    paddingVertical: 5,
    justifyContent: 'space-between',
    alignItems: 'center',
    // marginLeft: 15,
    paddingHorizontal: 15,
  },
  bck: {
    margin: 10,
    fontSize: fontsizes[5],
    backgroundColor: '#FFFF',
    width: 100,
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
    padding: 8,
    borderRadius: 5,
  },
  biotxt: {
    fontFamily: 'IRANSans-Bold',
    fontSize: fontsizes[3],
    color: 'grey',
    paddingVertical: 5,
    marginHorizontal: 10,
    // marginHorizontal: 10,
    marginBottom: 15,
  },
  biotxt2: {
    fontFamily: 'IRANSans-Bold',
    fontSize: fontsizes[5],
    color: 'grey',
    paddingVertical: 5,
    // marginHorizontal: 10,
    // marginBottom: 15,
  },
  biodestxt: {
    fontFamily: 'IRANSANS',
    fontSize: fontsizes[1],
    color: 'grey',
  },
  descview: {
    paddingTop: 10,
    paddingHorizontal: 20,
    marginHorizontal: 10,
    borderRadius: 10,
    backgroundColor: '#FFFF',
    marginTop: 25,
    paddingBottom: 25,
  },
  borderbott: {
    width: width * 0.9,
    borderBottomWidth: 0.5,
    borderBottomColor: '#d6dae3',
    alignSelf: 'center',
  },
  membertxt: {
    fontFamily: 'IRANSans-Bold',
    fontSize: fontsizes[3],
    color: '#969897',
    paddingVertical: 10,
  },
  timeview: {
    backgroundColor: '#112669',
    width: '25%',
    height: '100%',
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'space-around',
    // paddingVertical: 5,
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
  },
  touchtxt: {
    fontFamily: 'IRANSans-Bold',
    fontSize: fontsizes[0],
    color: '#FFFF',
  },
  programtxt: {
    width: '60%',
    marginLeft: 20,
    // paddingVertical: 5
    justifyContent: 'center',
    // backgroundColor: 'red',
  },
  txtprodes: {
    // backgroundColor: 'red'
    fontFamily: 'IRANSANS',
  },
  arroeright: {
    backgroundColor: '#57c9fd',
    position: 'absolute',
    alignSelf: 'center',
    zIndex: 2,
    right: 10,
    paddingHorizontal: 5,
    paddingVertical: 5,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  touchoricomm: {
    backgroundColor: '#FFFF',
    borderRadius: 10,
    width: width * 0.9,
    flexDirection: 'row',
    alignSelf: 'center',
    marginBottom: 15,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: {
          width: 0,
          height: 1.5,
        },
        shadowOpacity: 0.35,
        shadowRadius: 0.35,
      },
      android: {
        elevation: 3,
      },
    }),
  },
  backtouchimg: {
    paddingHorizontal: width * 0.08,
    height: '100%',
    marginHorizontal: 30,
    borderRadius: 5,
    overflow: 'hidden',
  },
  touchtxt: {
    fontFamily: 'IRANSans-Bold',
    fontSize: fontsizes[4],
    color: '#FFFF',
  },
  dateintouch: {
    fontFamily: 'IRANSANS',
    fontSize: fontsizes[1],
    color: '#FFFF',
  },
  arbtn: {
    position: 'absolute',
    zIndex: 4,
    right: 0,
    top: height * 0.8,
    width: 60,
    height: 50,
    borderTopLeftRadius: 25,
    borderBottomLeftRadius: 25,
    backgroundColor: '#6561fc',
    overflow: 'hidden',
    justifyContent: 'center',
    // alignItems: 'center',
    paddingHorizontal: 5,
  },
  arbtnimg: {
    width: 40,
    height: 40,
    borderRadius: 20,
    overflow: 'hidden',
  },
  arimgbtn: {
    width: '100%',
    height: '100%',
    // borderRadius: 30,
    // borderRadius: width * 0.1,
  },
  txttitledes: {
    fontFamily: 'IRANSANS',
  },
  txtproname: {
    fontFamily: 'IRANSANS',
  },
  txtbookmark: {
    position: 'absolute',
    top: height * 0.055,
    color: '#FFFF',
    fontFamily: 'IRANSANS',
  },
  topview: {
    width,
    // height: 270,
    paddingTop: height * 0.10,
    // backgroundColor: '#DB2227',
    zIndex: 10,
    justifyContent: 'center',
    alignItems: 'center',
    borderBottomLeftRadius: (width * 8) / 100,
    borderBottomRightRadius: (width * 8) / 100,
  },
});
