import { StyleSheet, Dimensions, I18nManager } from 'react-native';
const { width, height } = Dimensions.get('screen');
// const ffamilybold = I18nManager.isRTL ? 'IRANSANS' : 'TwCenMT-Bold';
// const ffamily = I18nManager.isRTL ? 'IRANSANS' : 'TwCenMT-Regular';
const fontsizes =
  width < 680 ? [9, 12, 14, 16, 18, 20] : [9, 14, 16, 18, 20, 24];
const IconSize = width < 680 ? [34, 32, 30, 28, 26] : [36, 34, 32, 30, 28];
export default StyleSheet.create({
  mainscrview: {
    backgroundColor: '#f0f4fd',
    height,
  },
  animindex: {
    position: 'absolute',
    zIndex: 5,
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: '#DB2227',
    overflow: 'hidden',
  },
  headermainscr: {
    height: height * 0.4,
    width,
    // borderBottomLeftRadius: (width * 25) / 100,
    // borderBottomRightRadius: (width * 25) / 100,
    backgroundColor: '#eaeef7',
    zIndex: 2,
  },
  arimgbtn: {
    width: '100%',
    height: '100%',
    // borderRadius: 30,
    // borderRadius: width * 0.1,
  },
  linearGradient: {
    height: '20%',
    width: '100%',
    // height: 90,
    position: 'absolute',
    top: 0,
    zIndex: 7,
    opacity: 0.2,
  },
  imgbackheader: {
    height: '100%',
    width: '100%',
    // borderBottomLeftRadius: (width * 10) / 100,
    // borderBottomRightRadius: (width * 10) / 100,
    // overflow: 'hidden',
  },
  txtbookm: {
    fontSize: fontsizes[4],
    fontFamily: 'IRANSANS',
    color: '#bababa',
  },
  bookview: {
    flexDirection: 'column',
    backgroundColor: '#FFFF',
    alignSelf: 'center',
    paddingVertical: 10,
    paddingHorizontal: 5,
    borderRadius: 10,
    top: height * 0.34,
    position: 'absolute',
    zIndex: 2,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: {
          width: 0,
          height: 1.5,
        },
        shadowOpacity: 0.35,
        shadowRadius: 0.35,
      },
      android: {
        elevation: 3,
      },
    }),
  },
  writenoteview: {
    width: width * 0.08,
    height: height * 0.035,
  },
  locviewexabit: {
    flexDirection: 'row',
    // backgroundColor: 'blue',
    justifyContent: 'space-around',
  },
  imgexhabitloc: {
    width: width * 0.06,
    height: height * 0.05,
    borderRadius: 5,
    marginHorizontal: 10,
  },
  imgexhabitnote: {
    width: '100%',
    height: '100%',
    // borderRadius: 5,
    // marginHorizontal: 10,
  },
  boxtopexhab: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  linebetw: {
    borderWidth: 1,
    borderColor: '#f8f8f8',
    marginVertical: 10,
  },
  txtimg: {
    fontSize: fontsizes[0],
    fontFamily: 'IRANSans-Bold',
    marginTop: 5,
  },
  bookcontain: {
    flexDirection: 'column',
    // paddingHorizontal: 15,
    width: width * 0.21,
    alignItems: 'center',
    justifyContent: 'center',
  },
  namedetail: {
    fontSize: fontsizes[3],
    fontFamily: 'IRANSans-Bold',
    color: '#a8a8a8',
  },
  viewnamedetail: {
    marginTop: height * 0.055,
    backgroundColor: '#FFFF',
    alignItems: 'center',
    paddingVertical: 10,
    marginBottom: 5,
  },
  bottcarevents: {
    flexDirection: 'row',
    padding: 5,
  },
  reeventbott: {
    flexDirection: 'row',
    paddingHorizontal: 10,
    alignItems: 'center',
  },
  imgbottcarevents: {
    width: width * 0.07,
    height: height * 0.04,
    marginHorizontal: 5,
  },
  txtcareventdate: {
    fontFamily: 'IRANSANS',
    fontSize: fontsizes[1],
    color: '#a6aaab',
  },
  addevedate: {
    flexDirection: 'row',
    paddingVertical: 5,
    justifyContent: 'space-between',
    alignItems: 'center',
    // marginLeft: 15,
    paddingHorizontal: 15,
  },
  biotxt: {
    fontFamily: 'IRANSANS',
    fontSize: fontsizes[3],
    color: '#a6aaab',
    paddingVertical: 5,
  },
  biodestxt: {
    fontFamily: 'IRANSANS',
    fontSize: fontsizes[1],
    color: '#b6b6b6',
  },
  descview: {
    paddingVertical: 20,
    paddingHorizontal: 10,
    // paddingBottom: 25,
    backgroundColor: '#FFFF',
    borderRadius: 20,
  },
  borderbott: {
    width: width * 0.9,
    borderBottomWidth: 0.5,
    borderBottomColor: '#b6b6b6',
    alignSelf: 'center',
  },
  membertxt: {
    fontFamily: 'IRANSANS',
    fontSize: fontsizes[3],
    color: '#a6aaab',
    paddingVertical: 10,
  },
  touchoricomm: {
    backgroundColor: '#FFFF',
    borderRadius: 10,
    width: width * 0.9,
    height: height * 0.11,
    flexDirection: 'row',
    alignSelf: 'center',
    marginVertical: 15,
    // alignItems: 'center',
  },
  touchoricommspeaker: {
    backgroundColor: '#FFFF',
    borderRadius: 10,
    width: width * 0.9,
    height: height * 0.1,
    flexDirection: 'row',
    alignSelf: 'center',
    marginVertical: 15,
    // alignItems: 'center',
  },
  backtouchimg: {
    paddingHorizontal: width * 0.1,
    height: '100%',
    marginHorizontal: 20,
    borderRadius: 5,
    overflow: 'hidden',
  },
  touchtxt: {
    fontFamily: 'IRANSANS',
    fontSize: fontsizes[3],
    // color: '#FFFF',
  },
  programtxt: {
    width: '50%',
    marginLeft: 10,
    paddingVertical: 10,
    // marginRight: 15,
    // backgroundColor: 'red',
  },
  programtxtname: {
    width: '50%',
    marginLeft: 10,
    paddingVertical: 10,
  },
  timeview: {
    width: '35%',
    // height: height * 0.1,
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
    backgroundColor: '#cec8ca',
  },
  timeviewspeaker: {
    width: '35%',
    // height: height * 0.1,
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
    backgroundColor: '#cec8ca',
  },
  arroeright: {
    // backgroundColor: 'red',
    position: 'absolute',
    alignSelf: 'center',
    zIndex: 2,
    // right: 2,
    // paddingHorizontal: 5,
    // paddingVertical: 5,
    // borderRadius: 5,
    // alignItems: 'center',
    // justifyContent: 'center',
  },
  txtprodes: {
    fontFamily: 'IRANSans-Bold',
    fontSize: fontsizes[2],
    // paddingTop: 2,
  },
  txtprodesname: {
    fontFamily: 'IRANSans-Bold',
    fontSize: fontsizes[2],
    // paddingTop: 2,
  },
  txtproname: {
    fontFamily: 'IRANSans-Bold',
    fontSize: fontsizes[1],
    color: '#9f9f9f',
  },
  txtpronamesd: {
    fontFamily: 'IRANSans-Bold',
    fontSize: fontsizes[1],
    color: '#9f9f9f',
    marginBottom: 5,
  },
  arrowimg: {
    height: height * 0.095,
    width: width * 0.085,
    borderRadius: 10,
    // overflow: 'hidden',
    position: 'absolute',
    alignSelf: 'center',
    zIndex: 2,
    right: 10,
  },
  arrowimgre: {
    height: height * 0.095,
    width: width * 0.085,
    borderRadius: 10,
    // overflow: 'hidden',
    // position: 'absolute',
    alignSelf: 'center',
    zIndex: 2,
    // right: 10,
  },
  arbtn: {
    position: 'absolute',
    zIndex: 4,
    right: 0,
    top: height * 0.8,
    width: 60,
    height: 50,
    borderTopLeftRadius: 25,
    borderBottomLeftRadius: 25,
    backgroundColor: '#6561fc',
    overflow: 'hidden',
    justifyContent: 'center',
    // alignItems: 'center',
    paddingHorizontal: 5,
  },
  arbtnimg: {
    width: 40,
    height: 40,
    borderRadius: 20,
    overflow: 'hidden',
  },
  arimgbtn: {
    width: '100%',
    height: '100%',
    // borderRadius: 30,
    // borderRadius: width * 0.1,
  },
  speachdet: {
    fontFamily: 'IRANSANS',
    fontSize: fontsizes[1],
    color: '#9f9f9f',
    marginTop: 5,
  },
});
