import {StyleSheet, Dimensions, I18nManager} from 'react-native';
const {width, height} = Dimensions.get('screen');
// const ffamilybold = I18nManager.isRTL ? 'IRANSANS' : 'TwCenMT-Bold';
// const ffamily = I18nManager.isRTL ? 'IRANSANS' : 'TwCenMT-Regular';
const fontsizes =
  width < 680 ? [9, 12, 14, 16, 18, 20] : [9, 14, 16, 18, 20, 24];
const IconSize = width < 680 ? [34, 32, 30, 28, 26] : [36, 34, 32, 30, 28];
export default StyleSheet.create({
  mainscrview: {
    backgroundColor: '#FFFF',
    height,
  },
  animindex: {
    position: 'absolute',
    zIndex: 5,
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: '#DB2227',
    overflow: 'hidden',
  },
  headermainscr: {
    height: height * 0.4,
    borderBottomLeftRadius: (width * 25) / 100,
    borderBottomRightRadius: (width * 25) / 100,
    // backgroundColor: 'green',
    // paddingBottom: 5,
  },
  imgbackheader: {
    width: (width * 100) / 100,
    height: '100%',
    borderBottomLeftRadius: (width * 10) / 100,
    borderBottomRightRadius: (width * 10) / 100,
    overflow: 'hidden',
  },
  imglinear: {
    width: (width * 100) / 100,
    height: '100%',
    borderBottomLeftRadius: (width * 5) / 100,
    borderBottomRightRadius: (width * 5) / 100,
    // overflow: 'hidden',
    // position: 'absolute',
    // zIndex: 2,
    opacity: 0.6,
  },
  txtbookm: {
    fontSize: fontsizes[3],
    fontFamily: 'IRANSans-Bold',
    color: 'black',
  },
  bookview: {
    backgroundColor: '#EFF3FE',
    // justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    // paddingVertical: 5,
    // paddingHorizontal: 35,
    height: height * 0.07,
    width: width,
    bottom: 0,
    position: 'absolute',
    zIndex: 2,
    borderTopRightRadius: width,
    borderTopLeftRadius: height,
    alignContent: 'space-between',
  },
  circlebackmg: {
    width: width,
    height: height * 0.3,
    // backgroundColor: '#EFF3FE',
    backgroundColor: 'red',
    justifyContent: 'center',
    zIndex: 500,
  },
  userimgtopview: {
    width: '15%',
    height: '100%',
    borderRadius: 200,
    // marginBottom: -200,
    marginTop: -20,
    overflow: 'hidden',
  },
  usericonimg: {
    height: '100%',
    width: '100%',
  },
  namedetail: {
    fontSize: fontsizes[4],
    fontFamily: 'IRANSans-Bold',
    color: '#303030',
    backgroundColor: '#FFFF',
    paddingHorizontal: 10,
    // position:"absolute",
    marginTop: -30,
  },
  viewnamedetail: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: height * 0.03,
    backgroundColor: '#FFFF',
    flexDirection: 'column',
    paddingVertical: 5,
    borderBottomColor: '#F9F9FB',
    borderBottomWidth: 2,
  },
  bottcarevents: {
    flexDirection: 'column',
    // padding: 5,
    // width: width - 10,
    // backgroundColor: 'green',
    justifyContent: 'flex-start',
  },
  reeventbott: {
    flexDirection: 'row',
    paddingHorizontal: '5%',
    alignItems: 'center',
    justifyContent: 'flex-start',
    direction: 'ltr',
    // backgroundColor: 'red'
  },
  imgbottcarevents: {
    width: width * 0.05,
    height: height * 0.04,
    marginRight: 10,
  },
  txtcareventdate: {
    fontFamily: 'IRANSans-Bold',
    fontSize: fontsizes[1],
    color: 'black',
    // backgroundColor: '#FFFF',
  },
  addevedate: {
    flexDirection: 'row',
    // paddingVertical: 5,
    justifyContent: 'center',
    alignItems: 'center',
    // marginLeft: 15,
    paddingHorizontal: '5%',
  },
  biotxt: {
    fontFamily: 'IRANSans',
    fontSize: fontsizes[2],

    // paddingVertical: 5,
    marginBottom: 10,
    color: '#B3B2B7',
  },
  rightbioview: {
    marginLeft: 10,
  },
  biodestxt: {
    fontFamily: 'IRANSANS',
    fontSize: fontsizes[1],
    color: 'black',
  },
  descview: {
    paddingTop: 10,
    paddingHorizontal: 20,
    paddingBottom: 25,
    flexDirection: 'row',
  },
  borderbott: {
    width: width * 0.9,
    borderBottomWidth: 0.5,
    borderBottomColor: '#d6dae3',
    alignSelf: 'center',
  },
  membertxt: {
    fontFamily: 'IRANSans-Bold',
    fontSize: fontsizes[3],
    color: '#969897',
    paddingVertical: 10,
  },
  touchoricomm: {
    // backgroundColor: '#57c9fd',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 15,
    paddingHorizontal: 40,
    borderRadius: 5,
    marginLeft: 25,
  },
  backtouchimg: {
    // position: 'absolute',
    // bottom: 0,
    // paddingHorizontal: width * 0.08,
    height: 70,
    width: width * 0.85,
    marginHorizontal: 35,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 5,
    overflow: 'hidden',
  },
  touchtxt: {
    fontFamily: 'IRANSans-Bold',
    fontSize: fontsizes[4],
    color: '#FFFF',
  },
  arbtn: {
    position: 'absolute',
    zIndex: 4,
    right: 0,
    top: height * 0.8,
    width: 60,
    height: 50,
    borderTopLeftRadius: 25,
    borderBottomLeftRadius: 25,
    backgroundColor: '#6561fc',
    overflow: 'hidden',
    justifyContent: 'center',
    // alignItems: 'center',
    paddingHorizontal: 5,
  },
  arbtnimg: {
    width: 40,
    height: 40,
    borderRadius: 20,
    overflow: 'hidden',
  },
  arimgbtn: {
    width: '100%',
    height: '100%',
    // borderRadius: 30,
    // borderRadius: width * 0.1,
  },
  iconnotebook: {
    color: '#8B8B8D',
  },
  biodescview: {
    borderWidth: 3,
    borderRadius: 5,
    borderColor: '#F9F9FB',

    padding: 10,
    width: width * 0.8,
  },
});
