const initialState = {
  ShortName:'test',
  Token: '',
  idevents: 0,
  splashOrNot: false,
  Notifications: [],
  InEvent: false,
  switchas: false,
  Pages: [
    {Id: 1, Name: 'Live Session', Status: false},
    {Id: 2, Name: 'Exhibitors & Sponsors', Status: false},
    {Id: 3, Name: 'Notifications', Status: false},
    {Id: 4, Name: 'Welcome Message', Status: false},
    {Id: 5, Name: 'Conference Guide', Status: false},
    {Id: 6, Name: 'Committees', Status: false},
    {Id: 7, Name: 'Speakers', Status: false},
    {Id: 8, Name: 'Scientific Program', Status: false},
    {Id: 9, Name: 'Symposia & Workshops', Status: false},
    {Id: 10, Name: 'Sponsors', Status: false},
    {Id: 11, Name: 'My picture', Status: false},
    {Id: 12, Name: 'Contact Us', Status: false},
    {Id: 13, Name: 'Conference Book', Status: false},
    {Id: 14, Name: 'Welcome Massage', Status: false},
    {Id: 15, Name: 'Symposia & Workshops', Status: false},
    {Id: 16, Name: 'Exhibitors & Sponsors', Status: false},
    {Id: 17, Name: 'Scientific Program', Status: false},
    {Id: 18, Name: 'Conference Book', Status: false},
    {Id: 19, Name: 'About AIDA 2021', Status: false},
    {
      Id: 20,
      Status: false,
      Name: 'name1',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 21,
      Status: false,
      Name: 'name2',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 22,
      Status: false,
      Name: 'name3',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 23,
      Status: false,
      Name: 'name4',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 24,
      Status: false,
      Name: 'name5',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 25,
      Status: false,
      Name: 'name6',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 26,
      Status: false,
      Name: 'name7',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 27,
      Status: false,
      Name: 'name8',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 28,
      Status: false,
      Name: 'name9',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 29,
      Status: false,
      Name: 'name10',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 30,
      Status: false,
      Name: 'name11',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 31,
      Status: false,
      Name: 'name12',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 32,
      Status: false,
      Name: 'name13',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 33,
      Status: false,
      Name: 'name14',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 34,
      Status: false,
      Name: 'name15',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 35,
      Status: false,
      Name: 'name16',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 36,
      Status: false,
      Name: 'name17',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 37,
      Status: false,
      Name: 'name18',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 38,
      Status: false,
      Name: 'name19',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 39,
      Status: false,
      Name: 'name20',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 40,
      Status: false,
      Name: 'name21',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 41,
      Status: false,
      Name: 'name22',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 42,
      Status: false,
      Name: 'name23',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 43,
      Status: false,
      Name: 'name24',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 44,
      Status: false,
      Name: 'name25',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 45,
      Status: false,
      Name: 'name26',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 46,
      Status: false,
      Name: 'name27',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 47,
      Status: false,
      Name: 'name28',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 48,
      Status: false,
      Name: 'name29',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 49,
      Status: false,
      Name: 'name30',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 50,
      Status: false,
      Name: 'name31',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 51,
      Status: false,
      Name: 'name32',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 52,
      Status: false,
      Name: 'name33',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 53,
      Status: false,
      Name: 'name34',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 54,
      Status: false,
      Name: 'name35',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 55,
      Status: false,
      Name: 'name36',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 56,
      Status: false,
      Name: 'name37',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 57,
      Status: false,
      Name: 'name38',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 58,
      Status: false,
      Name: 'name39',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 59,
      Status: false,
      Name: 'name40',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 60,
      Status: false,
      Name: 'name41',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 61,
      Status: false,
      Name: 'name42',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 62,
      Status: false,
      Name: 'name43',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 63,
      Status: false,
      Name: 'name44',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 64,
      Status: false,
      Name: 'name45',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 65,
      Status: false,
      Name: 'name46',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 66,
      Status: false,
      Name: 'name47',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 67,
      Status: false,
      Name: 'name48',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 68,
      Status: false,
      Name: 'name49',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 69,
      Status: false,
      Name: 'name50',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
    {
      Id: 70,
      Status: false,
      Name: 'name51',
      Image: '3.jpg',
      Url: '',
      File: 'https://backendApp.uaehybrid.com/Images/1.pdf',
    },
  ],
  itemdata: [],
  // Pages: [{ "Id": 1, "Name": "Live Session", "Status": false },
  // { "Id": 2, "Name": "Exhibitors & Sponsors", "Status": false },
  // { "Id": 3, "Name": "Notifications", "Status": false },
  // { "Id": 4, "Name": "Welcome Message", "Status": false },
  // { "Id": 5, "Name": "Conference Guide", "Status": false },
  // { "Id": 6, "Name": "Committees", "Status": false },
  // { "Id": 7, "Name": "Speakers", "Status": false },
  // { "Id": 8, "Name": "Scientific Program", "Status": false },
  // { "Id": 9, "Name": "Symposia & Workshops", "Status": false },
  // { "Id": 10, "Name": "Sponsors", "Status": false },
  // { "Id": 11, "Name": "My picture", "Status": false },
  // { "Id": 12, "Name": "Contact Us", "Status": false },
  // { "Id": 13, "Name": "Conference Book", "Status": false },
  // { "Id": 14, "Name": "Welcome Massage", "Status": false },
  // { "Id": 15, "Name": "Symposia & Workshops", "Status": false },
  // { "Id": 16, "Name": "Exhibitors & Sponsors", "Status": false },
  // { "Id": 17, "Name": "Scientific Program", "Status": false },
  // { "Id": 18, "Name": "Conference Book", "Status": false },
  // { "Id": 19, "Name": "About AIDA 2021", "Status": false }],
};
const Customer = (state = initialState, action) => {
  // console.log(action)
  switch (action.type) {
    case 'CHANGE_C_Token':
      return {...state, Token: action.Token};
    case 'CHANGE_C_splashOrNot':
      return {...state, splashOrNot: action.splashOrNot};
    case 'CHANGE_C_Pages':
      return {...state, Pages: action.Pages};
    case 'CHANGE_C_switchas':
      return {...state, switchas: action.switchas};
    case 'CHANGE_C_InEvent':
      return {...state, InEvent: action.InEvent};
    case 'CHANGE_C_idevents':
      return {...state, idevents: action.idevents};
    case 'CHANGE_C_Notifications':
      return {...state, Notifications: action.Notifications};
    case 'CHANGE_C_itemdata':
      return {...state, itemdata: action.itemdata};
    case 'CHANGE_C_ShortName':
      return {...state, ShortName: action.ShortName};
    default:
      return state;
  }
};

export default Customer;
