import { StyleSheet, Dimensions, I18nManager } from 'react-native';
const { width, height } = Dimensions.get('screen');
// const ffamilybold = I18nManager.isRTL ? 'IRANSANS' : 'TwCenMT-Bold';
// const ffamily = I18nManager.isRTL ? 'IRANSANS' : 'TwCenMT-Regular';
const fontsizes =
  width < 680 ? [9, 12, 14, 16, 18, 20] : [9, 14, 16, 18, 20, 24];
const IconSize = width < 680 ? [34, 32, 30, 28, 26] : [36, 34, 32, 30, 28];
export default StyleSheet.create({
  mainscrview: {
    backgroundColor: '#f0f4fd',
    height,
  },
  TxtHeder: {
    width: '100%',
    backgroundColor: '#FFFF',
    paddingVertical: 5,
    color: 'grey',
    textAlign: 'center',
    marginVertical: 10,
  },
  imgexhabitnote: {
    width: width * 0.05,
    height: height * 0.04,
    borderRadius: 5,
    // marginHorizontal: 10,
  },
  writenoteview: {
    paddingHorizontal: 15,
    alignItems: 'center',
  },
  txtdate: {
    color: '#FFFF',
    fontFamily: 'IRANSans-Bold',
    fontSize: fontsizes[1],
    // paddingHorizontal: 3,
  },
  txtinp: {
    width: '60%',
    borderRadius: 10,
    color: '#bcbec7',
    fontFamily: 'IRANSans-Bold',
    fontSize: fontsizes[2],
    paddingHorizontal: 5,
    // fontSize: fontsizes[3],
  },
  txtinptouch: {
    // width: '30%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
    borderRadius: 10,
    paddingVertical: 10,
    marginLeft: 5,
    backgroundColor: '#29cff9',
  },
  viewinRate: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  viewtxtinp: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: width * 0.9,
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: '#FFFF',
    position: 'absolute',
    // top: height * 0.37,
    bottom: -25,
    zIndex: 10,
    paddingVertical: 5,
    borderRadius: 15,
    paddingHorizontal: 5,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: {
          width: 0,
          height: 1.5,
        },
        shadowOpacity: 0.35,
        shadowRadius: 0.35,
      },
      android: {
        elevation: 3,
      },
    }),
  },
  animindex: {
    position: 'absolute',
    zIndex: 5,
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: '#DB2227',
    overflow: 'hidden',
  },
  headermainscr: {
    height: height * 0.41,
    width,
    overflow: 'hidden',
    borderBottomLeftRadius: (width * 10) / 100,
    borderBottomRightRadius: (width * 10) / 100,
    backgroundColor: '#eaeef7',
    zIndex: 2,
  },
  linearGradient: {
    height: '20%',
    width: '100%',
    // height: 90,
    position: 'absolute',
    top: 0,
    zIndex: 7,
    opacity: 0.2,
  },
  imgbackheader: {
    height: '100%',
    width: '100%',
    // borderBottomLeftRadius: (width * 10) / 100,
    // borderBottomRightRadius: (width * 10) / 100,
    // overflow: 'hidden',
  },
  txtbookm: {
    fontSize: fontsizes[4],
    fontFamily: 'IRANSANS',
    color: '#bababa',
  },
  bookview: {
    flexDirection: 'column',
    backgroundColor: '#FFFF',
    alignSelf: 'center',
    paddingVertical: 10,
    paddingHorizontal: 5,
    borderRadius: 10,
    top: height * 0.35,
    // bottom: -50,
    position: 'absolute',
    zIndex: 2,
  },
  writenoteview: {
    // padding: 5,
    // marginTop: 10,
    borderRightWidth: .5,
    paddingRight: 10,
    borderColor: 'grey',

    alignItems: 'center',
    // width: '30%',
    alignSelf: 'center',
    // margin: 10,
    // borderRadius: 10,
    // backgroundColor: '#FFFF',
  },
  locviewexabit: {
    flexDirection: 'row',
    // backgroundColor: 'blue',
    justifyContent: 'space-around',
  },
  imgexhabitloc: {
    width: width * 0.06,
    height: height * 0.05,

    // marginHorizontal: 10,
  },
  imgexhabitnote: {
    width: width * 0.05,
    height: height * 0.038,
    borderRadius: 5,
    backgroundColor: '#FFFF'
    // marginHorizontal: 10,
  },
  boxtopexhab: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  linebetw: {
    borderWidth: 1,
    borderColor: '#f8f8f8',
    marginVertical: 10,
  },
  txtimg: {
    fontSize: fontsizes[1],
    fontFamily: 'IRANSANS',
  },
  namedetail: {
    fontSize: fontsizes[2],
    fontFamily: 'IRANSans-Bold',
    color: '#a2a2a2',
    paddingHorizontal: 15,
    textAlign: 'justify',
  },
  viewnamedetail: {
    marginTop: height * 0.04,
    backgroundColor: '#FFFF',
    alignItems: 'center',
    paddingVertical: 15,
  },
  bottcarevents: {
    flexDirection: 'row',
    padding: 5,
    // backgroundColor: 'red',
    // justifyContent: 'space-between',
  },
  reeventbott: {
    flexDirection: 'row',
    paddingHorizontal: 10,
    alignItems: 'center',
  },
  imgbottcarevents: {
    width: width * 0.07,
    height: height * 0.04,
    marginHorizontal: 5,
  },
  txtcareventdate: {
    fontFamily: 'IRANSANS',
    fontSize: fontsizes[1],
    color: '#a6aaab',
  },
  addevedate: {
    flexDirection: 'row',
    paddingVertical: 5,
    justifyContent: 'space-between',
    alignItems: 'center',
    // marginLeft: 15,
    paddingHorizontal: 15,
  },
  biotxt: {
    fontFamily: 'IRANSANS',
    fontSize: fontsizes[3],
    color: '#a6aaab',
    paddingVertical: 5,
  },
  biodestxt: {
    fontFamily: 'IRANSANS',
    fontSize: fontsizes[1],
    color: '#b6b6b6',
  },
  descview: {
    paddingTop: 10,
    paddingHorizontal: 20,
    // paddingBottom: 25,
    // backgroundColor: 'red',
  },
  borderbott: {
    width: width * 0.9,
    borderBottomWidth: 0.5,
    borderBottomColor: '#b6b6b6',
    alignSelf: 'center',
  },
  membertxt: {
    fontFamily: 'IRANSANS',
    fontSize: fontsizes[3],
    color: '#a6aaab',
    paddingVertical: 10,
  },
  touchoricomm: {
    backgroundColor: '#FFFF',
    borderRadius: 15,
    width: width * 0.9,
    flexDirection: 'row',
    // height: height * 0.1,
    alignSelf: 'center',
    marginBottom: 15,
  },
  backtouchimg: {
    paddingHorizontal: width * 0.1,
    height: '100%',
    marginHorizontal: 20,
    borderRadius: 5,
    overflow: 'hidden',
  },
  touchtxt: {
    fontFamily: 'IRANSans-Bold',
    fontSize: fontsizes[3],
    color: '#FFFF',
  },
  programtxt: {
    width: '72%',
    marginLeft: 10,
    paddingVertical: 15,
  },
  programtxt2: {
    width: '65%',
    marginLeft: 10,
    paddingVertical: 15,
  },
  timeview: {
    backgroundColor: '#112669',
    width: '25%',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingVertical: 10,
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
  },
  arroeright: {
    // backgroundColor: '#57c9fd',
    position: 'absolute',
    alignSelf: 'center',
    zIndex: 2,
    right: 10,
    // paddingHorizontal: 5,
    // paddingVertical: 5,
    // borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  txtprodes: {
    fontFamily: 'IRANSans-Bold',
    fontSize: fontsizes[3],
  },
  txtproname: {
    fontFamily: 'IRANSANS',
    fontSize: fontsizes[2],
    color: '#9f9f9f',
  },
  arrowimg: {
    height: width * 0.1,
    width: width * 0.1,
  },
  arbtn: {
    position: 'absolute',
    zIndex: 4,
    right: 0,
    top: height * 0.8,
    width: 60,
    height: 50,
    borderTopLeftRadius: 25,
    borderBottomLeftRadius: 25,
    backgroundColor: '#6561fc',
    overflow: 'hidden',
    justifyContent: 'center',
    // alignItems: 'center',
    paddingHorizontal: 5,
  },
  arbtnimg: {
    width: 40,
    height: 40,
    borderRadius: 20,
    overflow: 'hidden',
  },
  arimgbtn: {
    width: '100%',
    height: '100%',
    // borderRadius: 30,
    // borderRadius: width * 0.1,
  },
});
