import {StyleSheet, Dimensions, I18nManager} from 'react-native';
const {width, height} = Dimensions.get('screen');
// const ffamilybold = I18nManager.isRTL ? 'IRANSANS' : 'TwCenMT-Bold';
// const ffamily = I18nManager.isRTL ? 'IRANSANS' : 'TwCenMT-Regular';
const fontsizes =
  width < 680
    ? [9, 12, 14, 16, 18, 20, 24, 26, 30]
    : [9, 14, 16, 18, 20, 24, 26, 28, 32];
const IconSize = width < 680 ? [34, 32, 30, 28, 26] : [36, 34, 32, 30, 28];
export default StyleSheet.create({
  mainview: {
    width: '90%',
    height: '90%',
    // backgroundColor: 'red',
  },
  mainscrview: {
    backgroundColor: '#f0f4fd',
    height,
    flex: 1,
    height: '100%',
    // width,
  },
  animindex: {
    position: 'absolute',
    zIndex: 5,
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: '#DB2227',
    overflow: 'hidden',
  },
  headermainscr: {
    width,
    // height: '28%',
    paddingTop: height * 0.13,
    backgroundColor: '#DB2227',
    zIndex: 10,
    borderBottomLeftRadius: (width * 8) / 100,
    borderBottomRightRadius: (width * 8) / 100,
  },
  gapview: {
    width: '100%',
    height: height * 0.05,
    zIndex: 2,
  },
  bodymainscr: {
    // height: height * 0.6,
    // backgroundColor: 'red',
    // marginTop: 1,
  },
  touchflatmain: {
    // height: (height * 5) / 100,
    backgroundColor: '#FFFF',
    // borderWidth: 1,
    marginVertical: 20,
    marginHorizontal: 5,
    paddingHorizontal: 20,
    paddingVertical: 5,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  touchflatmainall: {
    // height: (height * 5) / 100,
    backgroundColor: '#26cff6',
    // borderWidth: 1,
    marginVertical: 20,
    marginLeft: 15,
    paddingHorizontal: 20,
    paddingVertical: 5,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  flathorizmscr: {
    fontFamily: 'IRANSANS',
    fontSize: fontsizes[1],
  },
  textmainscrsec: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 20,
    marginTop: 5,
    marginBottom: 10,
    // backgroundColor: 'red',
  },
  txtmscrhead: {
    fontFamily: 'IRANSans-Bold',
    fontSize: fontsizes[3],
    color: '#4b4b4b',
  },
  txtviewall: {
    textDecorationLine: 'underline',
    color: '#2F9FD5',
    fontFamily: 'IRANSans-Bold',
  },
  touchmscrsec: {
    backgroundColor: 'red',
    // height: '30%',
  },
  mainscrcarview: {
    backgroundColor: '#FFFF',
    height: height * 0.5,
    borderRadius: 15,
    marginBottom: 15,
    paddingHorizontal: 15,
  },
  imgcarmainscr: {
    width: '100%',
    height: '55%',
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
  },
  reeventscardate: {
    flexDirection: 'column',
    backgroundColor: '#005EAB',
    position: 'absolute',
    right: 5,
    top: -10,
    paddingHorizontal: 12,
    // paddingVertical: 5,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  addeventsdate: {
    flexDirection: 'column',
    backgroundColor: '#2F9FD5',
    position: 'absolute',
    right: 0,
    top: -25,
    paddingHorizontal: 15,
    // paddingVertical: 5,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  reeventscar: {
    flexDirection: 'row',
    paddingTop: 15,
    paddingHorizontal: 2,
    // backgroundColor: 'red',
  },
  addeventstitle: {
    flexDirection: 'row',
    paddingTop: 20,
    // paddingHorizontal: 10,
    // backgroundColor: 'red',
  },
  txtreevents: {
    fontFamily: 'IRANSans-Bold',
    fontSize: fontsizes[2],
  },
  txtcarmainloc: {
    fontFamily: 'IRANSans-Bold',
    fontSize: fontsizes[1],
    color: '#FFFF',
  },
  txtcarnum: {
    fontFamily: 'IRANSans-Bold',
    fontSize: fontsizes[3],
    color: '#FFFF',
    // lineHeight: 0.1,
  },
  reeventbott: {
    width: width * 0.3,
    flexDirection: 'row',
    paddingVertical: 10,
    alignItems: 'center',
  },
  addevedate: {
    flexDirection: 'row',
    paddingVertical: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 15,
  },
  imgbottcarevents: {
    width: '100%',
    height: '100%',
    marginHorizontal: 3,
  },
  imgbottcarview: {
    width: width * 0.05,
    height: height * 0.03,
    marginRight: 10,
  },

  imgbottcareventssec: {
    width: '100%',
    height: '100%',
    // marginHorizontal: 5,
  },
  bottcarevents: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    // paddingVertical: 5,
    // backgroundColor: 'red',
  },
  txtcareventdate: {
    fontFamily: 'IRANSans-Bold',
    fontSize: fontsizes[0],
  },
  heartstyle: {
    position: 'absolute',
    zIndex: 2,
    height: '10%',
    width: '15%',
    top: 10,
    right: 10,
  },

  txtview: {
    paddingVertical: 5,
    paddingHorizontal: 10,
  },
  toptextheader: {
    color: '#FFFF',
    fontSize: fontsizes[7],
    fontFamily: 'TwCenMT-Bold',
    // fontFamily: 'IRANSans-Bold',
    paddingVertical: 5,
  },
  secondtextheader: {
    color: '#FFFF',
    fontSize: fontsizes[2],
    fontFamily: 'TwCenMT-Regular',
  },
  viewtxtinp: {
    flexDirection: 'row',
    // paddingHorizontal: 10,
    paddingVertical: 20,
    alignSelf: 'center',
    marginBottom: 40,
  },
  txtinpheader: {
    width: (width * 85) / 100,
    backgroundColor: '#FFFF',
    flexDirection: 'row-reverse',
    borderRadius: 10,
    alignItems: 'center',
    // marginBottom: 30,
  },
  txtinp: {
    width: '85%',
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
    // color: '#bcbec7',
    fontSize: fontsizes[3],
    fontFamily: 'IRANSans-Bold',
    alignItems: 'center',
  },
  txtinptouch: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 5,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
  },
  menutxtinpIcon: {
    color: '#bcbec7',
  },
  touchfilter: {
    backgroundColor: '#2F9FD5',
    marginLeft: 5,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    paddingHorizontal: 15,
  },
  filterpng: {
    width: width * 0.05,
    height: height * 0.05,
  },
  viewtxtinptoast: {
    flexDirection: 'row',
    justifyContent: 'center',
    width: width * 0.9,
    alignSelf: 'center',
    backgroundColor: '#FFFF',
    position: 'absolute',
    top: height * 0.2,
    zIndex: 10,
    paddingVertical: 15,
    borderRadius: 15,
    paddingHorizontal: 20,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: {
          width: 0,
          height: 1.5,
        },
        shadowOpacity: 0.35,
        shadowRadius: 0.35,
      },
      android: {
        elevation: 3,
      },
    }),
  },
  txtinptoast: {
    width: '60%',
    borderRadius: 10,
    color: '#bcbec7',
    fontFamily: 'IRANSans-Bold',
    fontSize: fontsizes[2],
    paddingHorizontal: 5,
    // backgroundColor: 'red',
    // fontSize: fontsizes[3],
  },
  txtinptouchtoast: {
    width: '30%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 5,
    borderRadius: 10,
    backgroundColor: '#29cff9',
  },
  txtdatetoast: {
    color: '#FFFF',
    fontFamily: 'IRANSans-Bold',
    fontSize: fontsizes[1],
    // paddingHorizontal: 3,
  },
  facuilityimg: {
    width: 30,
    height: 30,
    borderRadius: 60,
    marginLeft: -10,
  },
  bottomfacuilview: {
    height: 50,
    // backgroundColor: 'red',
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
  },
  facuilimgview: {
    flexDirection: 'row',
  },
});
