import { StyleSheet, Dimensions, I18nManager } from 'react-native';
const { width, height } = Dimensions.get('screen');
// const ffamilybold = I18nManager.isRTL ? 'IRANSANS' : 'TwCenMT-Bold';
// const ffamily = I18nManager.isRTL ? 'IRANSANS' : 'TwCenMT-Regular';
const fontsizes =
  width < 680 ? [9, 12, 14, 16, 18, 20] : [9, 14, 16, 18, 20, 24];
const IconSize = width < 680 ? [34, 32, 30, 28, 26] : [36, 34, 32, 30, 28];
export default StyleSheet.create({
  mainscrview: {
    backgroundColor: '#f0f4fd',
    height,
  },
  animindex: {
    position: 'absolute',
    zIndex: 5,
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: '#DB2227',
    overflow: 'hidden',
  },
  headermainscr: {
    height: height * 0.4,
    width,
    borderBottomLeftRadius: (width * 8) / 100,
    borderBottomRightRadius: (width * 8) / 100,
    overflow: 'hidden',
    backgroundColor: '#eaeef7',
    zIndex: 2,
  },
  linearGradient: {
    height: '20%',
    width: '100%',
    // height: 90,
    position: 'absolute',
    top: 0,
    zIndex: 7,
    opacity: 0.2,
  },
  imgbackheader: {
    height: '100%',
    width: '100%',
    // borderBottomLeftRadius: (width * 10) / 100,
    // borderBottomRightRadius: (width * 10) / 100,
    // overflow: 'hidden',
  },
  commentbox: {
    backgroundColor: '#FFFF',
    marginHorizontal: width * 0.05,
    // height: height * 0.6,
    marginTop: 25,
    borderTopRightRadius: 30,
    borderTopLeftRadius: 30,
  },
  addrate: {
    backgroundColor: '#2F9FD5',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    paddingLeft: 15,
    borderTopRightRadius: 15,
    borderTopLeftRadius: 15,
    overflow: 'hidden',
  },
  rateview: {
    backgroundColor: '#FFFF',
    paddingHorizontal: 20,
    paddingVertical: 5,
    borderRadius: 20,
  },
  addtouch: {
    backgroundColor: '#FFFF',
    paddingHorizontal: 20,
    paddingVertical: 2,
    alignItems: 'center',
    justifyContent: 'center',
    borderTopLeftRadius: 20,
    borderBottomLeftRadius: 20,
  },
  txtaddcomment: {
    fontFamily: 'IRANSans-Bold',
    fontSize: fontsizes[2],
    color: '#2F9FD5',
  },
  boxcomment: {
    marginHorizontal: '5%',
    backgroundColor: '#f0f4fd',
    // paddingHorizontal: 5,
    borderRadius: 10,
    marginTop: 15,
  },
  imgvcomment: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 5,
    // paddingHorizontal: 5,
  },
  imguser: {
    width: width * 0.08,
    height: width * 0.08,
    borderRadius: width * 0.08,
    marginRight: 10,
  },
  txtname: {
    fontFamily: 'IRANSans-Bold',
    fontSize: fontsizes[3],
    color: '#5a5a5a',
  },
  txtdes: {
    fontFamily: 'IRANSANS',
    fontSize: fontsizes[2],
    color: '#3a3a3a',
  },
  arbtn: {
    position: 'absolute',
    zIndex: 4,
    right: 0,
    top: height * 0.8,
    width: 60,
    height: 50,
    borderTopLeftRadius: 25,
    borderBottomLeftRadius: 25,
    backgroundColor: '#6561fc',
    overflow: 'hidden',
    justifyContent: 'center',
    // alignItems: 'center',
    paddingHorizontal: 5,
  },
  arbtnimg: {
    width: 40,
    height: 40,
    borderRadius: 20,
    overflow: 'hidden',
  },
  txtinp: {
    paddingHorizontal: 10,
  },
  usercomm: {
    // height: '40%',
    // backgroundColor: 'blue',
  },
  posttxt: {
    fontFamily: 'IRANSans-Bold',
    fontSize: fontsizes[1],
    backgroundColor: '#d3e1fc',
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    textAlign: 'center',
    color: '#4b5463',
    paddingVertical: 2,
    // marginVertical: 3,
  },
  arimgbtn: {
    width: '100%',
    height: '100%',
    // borderRadius: 30,
    // borderRadius: width * 0.1,
  },
});
