import { StyleSheet, Dimensions } from 'react-native';
const { width, height } = Dimensions.get('screen');
// const ffamilybold = I18nManager.isRTL ? 'IRANSANS' : 'TwCenMT-Bold';
// const ffamily = I18nManager.isRTL ? 'IRANSANS' : 'TwCenMT-Regular';
const fontsizes =
  width < 680 ? [9, 10, 12, 14, 16, 18, 20] : [9, 12, 14, 16, 18, 20, 24];
const IconSize = width < 680 ? [34, 32, 30, 28, 26] : [36, 34, 32, 30, 28];
export default StyleSheet.create({
  mainscrview: {
    backgroundColor: '#f0f4fd',
    height,
    paddingTop:'2%'
  },
  headermainscr: {
    height: height * 0.15,
    overflow: 'hidden',
    marginTop: height * 0.09,
    borderRadius: 10,
    marginHorizontal: 5,
    // borderBottomLeftRadius: (width * 10) / 100,
    // borderBottomRightRadius: (width * 10) / 100,
    backgroundColor: '#f0f4fd',
    marginBottom: 10,
    zIndex: 2,
  },
  adsbottomslider: {
    height: height * 0.15,
    width: width - 10,
    backgroundColor: '#f0f4fd',
    marginBottom: 10,
    zIndex: 2,
    marginTop: 5,
  },
  bodyscreen: {
    height: height * 0.6,
    // backgroundColor: 'yellow',
  },
  titletopbox: {
    borderWidth: 1,
    width: width * 0.8,
    borderColor: '#e0e0e0',
    alignSelf: 'center',
  },
  viewtopbox: {
    // backgroundColor: '#FFFF',
    marginHorizontal: '5%',
    // justifyContent: 'center',
    // alignItems: 'center',
    // borderRadius: 20,
    paddingVertical: 10,
    // ...Platform.select({
    //   ios: {
    //     shadowColor: '#000',
    //     shadowOffset: {
    //       width: 0,
    //       height: 1,
    //     },
    //     shadowOpacity: 0.35,
    //     shadowRadius: 0.35,
    //   },
    //   android: {
    //     elevation: 3,
    //   },
    // }),
    // marginVertical: 5,
    // position: 'absolute',
    // zIndex: 2,
  },
  txttopbox: {
    color: '#797979',
    fontSize: fontsizes[3],
    fontFamily: 'IRANSans-Bold',
    marginBottom: 5,
    marginTop: 5,
    textAlign: 'center',
    // backgroundColor: 'red',
  },
  bottomtbox: {
    marginTop: 10,
    // justifyContent: 'center',
    // width: '100%',
    // backgroundColor: 'red',
    alignItems: 'center',

    justifyContent: 'center',
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    overflow: 'hidden',

    // backgroundColor: 'green',
  },
  facultylist: {
    fontSize: fontsizes[4],
    fontFamily: 'IRANSans-Bold',
    color: '#413d3a',
    marginHorizontal: 20,
    marginTop: 10,
    marginBottom: 10,
  },
  facultypersonv: {
    backgroundColor: '#eaeaea',
    marginHorizontal: 3,
    justifyContent: 'center',
    alignItems: 'center',
    width: width * 0.1,
    height: width * 0.1,
    borderRadius: width * 0.1,
    overflow: 'hidden',
  },
  facultyaddnum: {
    backgroundColor: '#2F9FD5',
    // marginHorizontal: 3,
    marginRight: 15,
    justifyContent: 'center',
    alignItems: 'center',
    width: width * 0.1,
    height: width * 0.1,
    borderRadius: width * 0.05,
  },
  facultypersonimg: {
    width: '100%',
    height: '100%',
  },
  flatGrowB: {
    justifyContent: 'center',
    alignItems: 'center',
    margin: 5,
    marginHorizontal: 0,

    // backgroundColor: 'red',
  },
  txtnum: {
    fontSize: fontsizes[1],
    fontFamily: 'IRANSANS',
    color: '#FFFF',
  },
  txtgbuis: {
    fontSize: fontsizes[2],
    // fontFamily: 'IRANSans-Bold',
    color: '#151515',
    // marginTop: 5,
    // backgroundColor: 'red',
    marginBottom: 5,
    textAlign: 'center',
  },
  txtgbuis2: {
    fontSize: fontsizes[2],
    fontFamily: 'IRANSans-Bold',
    color: '#7c76b2',
    // marginTop: 5,
    // backgroundColor: 'red',
    // marginBottom: 5,
    textAlign: 'center',
  },
  textmainscrsec: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 20,
    marginBottom: 10,
  },
  txtmscrhead: {
    fontFamily: 'IRANSans-Bold',
    fontWeight: 'bold',
    color: '#413d3a',
    fontSize: fontsizes[5],
  },
  txtmscrheadc0mmitt: {
    fontFamily: 'IRANSans-Bold',
    fontWeight: 'bold',
    color: '#413d3a',
    fontSize: fontsizes[3],
  },
  viewall: {
    fontFamily: 'IRANSans-Bold',
    fontSize: fontsizes[3],
    fontWeight: 'bold',
    color: '#2F9FD5',
    textDecorationLine: 'underline',
  },
  mainscrcarview: {
    backgroundColor: '#FFFF',
    height: height * 0.23,
    // width: width * 0.7,
    borderRadius: 15,
    // paddingHorizontal: 15,
  },
  commitecar: {
    backgroundColor: '#FFFF',
    height: height * 0.15,
    borderRadius: 15,
    // marginHorizontal: 15,
    // backgroundColor: 'red',
    // paddingHorizontal: 15,
  },
  heartstyle: {
    position: 'absolute',
    zIndex: 2,
    height: '10%',
    width: '15%',
    top: 10,
    right: 10,
  },
  imgcarmainscr: {
    width: '100%',
    height: '60%',
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
    overflow: 'hidden',
  },
  imgcommite: {
    width: '100%',
    height: '90%',
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
    overflow: 'hidden',
  },
  addeventstitle: {
    flexDirection: 'row',
    paddingTop: 10,
    paddingHorizontal: 1,
    marginLeft:10
    // backgroundColor: 'red',
  },
  txtreevents: {
    fontFamily: 'IRANSANS',
    fontSize: fontsizes[2],
    // fontWeight: 'bold',
  },
  addeventsdate: {
    flexDirection: 'column',
    backgroundColor: '#2F9FD5',
    position: 'absolute',
    right: 10,
    top: -18,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 7,
    justifyContent: 'center',
    alignItems: 'center',
  },
  profileimg: {
    marginBottom: 15,
    paddingLeft: 15,
    flexDirection: 'row',
    backgroundColor: '#FFFF',
    // justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 5,
    // backgroundColor: 'red',
  },
  addeventsdatearrow: {
    // flexDirection: 'column',
    backgroundColor: '#2F9FD5',
    position: 'absolute',
    right: 10,
    top: -20,
    // paddingHorizontal: 5,
    // paddingVertical: 5,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  arrowright: {
    color: '#FFFF',
    fontSize: IconSize[2],
  },
  txtcarmainloc: {
    fontFamily: 'IRANSANS',
    fontSize: fontsizes[4],
    color: '#FFFF',
  },
  reeventbott: {
    width: width * 0.35,
    flexDirection: 'row',
    // paddingVertical: 10,
    paddingHorizontal: 5,
    // justifyContent: 'space-between',
    alignItems: 'center',
    // backgroundColor: 'green',
  },
  imglocview: {
    width: width * 0.05,
    height: width * 0.04,
    // padding: 5,
  },
  imgbottcarevents: {
    width: '100%',
    height: '100%',
    marginHorizontal: 3,
  },
  txtcareventdate: {
    fontFamily: 'IRANSANS',
    fontSize: fontsizes[1],
    marginLeft: 10,
  },
  addevedate: {
    width: width * 0.35,
    flexDirection: 'row',
    paddingVertical: 10,
    // justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 15,
    // backgroundColor: 'red',
  },
  bottcarevents: {
    flexDirection: 'row',
    paddingHorizontal: 5,
    // backgroundColor: 'red',
    // justifyContent: 'space-between',
  },

  commercialview: {
    height: height * 0.13,
    // width: width * 0.45,
    backgroundColor: '#FFFF',
    marginTop: 10,
    borderRadius: 5,
    marginLeft: 15,
    overflow: 'hidden',
    borderColor: 'grey',
    borderWidth: 0.2,
  },
  arbtn: {
    position: 'absolute',
    zIndex: 4,
    right: 0,
    top: height * 0.8,
    width: 60,
    height: 50,
    borderTopLeftRadius: 25,
    borderBottomLeftRadius: 25,
    backgroundColor: '#6561fc',
    overflow: 'hidden',
    justifyContent: 'center',
    // alignItems: 'center',
    paddingHorizontal: 5,
  },
  arbtnimg: {
    width: 40,
    height: 40,
    borderRadius: 20,
    overflow: 'hidden',
  },
  linearGradient: {
    height: '20%',
    width: '100%',
    // height: 90,
    position: 'absolute',
    top: 0,
    zIndex: 7,
    opacity: 0.2,
  },
  arimgback: {
    width: width * 0.12,
    height: width * 0.12,
    borderRadius: width * 0.12,
    padding: 7,
    backgroundColor: '#FFFF',
  },
  arimgbtn: {
    width: '100%',
    height: '100%',
    // borderRadius: 30,
    // borderRadius: width * 0.1,
  },
  imgbackheader: {
    height: '100%',
    width: '100%',
    // borderBottomLeftRadius: (width * 10) / 100,
    // borderBottomRightRadius: (width * 10) / 100,
    // overflow: 'hidden',
  },
  viewtxtinp: {

    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '96%',
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: '#FFFF',
    // position: 'absolute',
    // top: height * 0.37,
    // bottom: -28,
    zIndex: 10,
    padding: 7,
    borderRadius: 15,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: {
          width: 0,
          height: 1.5,
        },
        shadowOpacity: 0.35,
        shadowRadius: 0.35,
      },
      android: {
        elevation: 3,
      },
    }),
  },
  txtinpheader: {
    backgroundColor: '#FFFF',
    flexDirection: 'row-reverse',
    borderRadius: 10,
    paddingHorizontal: 5,
  },
  txtdate: {
    color: '#FFFF',
    fontFamily: 'IRANSans-Bold',
    fontSize: fontsizes[3],
    // paddingHorizontal: 3,
  },
  animindex: {
    position: 'absolute',
    zIndex: 5,
    top: 0,
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    overflow: 'hidden',
  },
  txtinp: {
    width: '65%',
    borderRadius: 10,
    color: '#696969',
    fontFamily: 'IRANSans-Bold',
    fontSize: fontsizes[2],
    paddingHorizontal: 5,
    textAlign: 'auto'
    // fontSize: fontsizes[3],
  },
  txtinptouch: {
    width: '30%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
    borderRadius: 10,
    paddingVertical: 10,
    backgroundColor: '#29cff9',
  },
  txtinptouch2: {
    flexDirection: 'row',
    width: '35%',
    height: '100%',
    alignItems: 'flex-start',
    justifyContent: 'space-around',
    paddingHorizontal: 10,
    borderRadius: 10,
    paddingVertical: 10,
    // backgroundColor: 'red',
    backgroundColor: '#e64c3c',
  },
  menutxtinpIcon: {
    color: '#6694fc',
    fontSize: IconSize[1],
    paddingVertical: 10,
  },
  botomtoast: {
    width: width * 0.7,
    height: height * 0.07,
    borderRadius: 15,
    zIndex: -5,
    alignSelf: 'center',
    backgroundColor: '#f5f5f5',

    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: {
          width: 0,
          height: 3,
        },
        shadowOpacity: 0.1,
        shadowRadius: 0.1,
      },
      android: {
        elevation: 2.5,
      },
    }),
  },
  mapviews: {
    marginVertical: 10,
    height: height * 0.2,
    marginHorizontal: 20,
    backgroundColor: '#FFFF',
  },
  maptxt: {
    marginTop: 5,
  },
  video: {
    marginHorizontal: 20,
    height: height * 0.2,
  },
});
