import {StyleSheet, Dimensions, I18nManager} from 'react-native';
import {fontsizes, ffamily, ffamilybold, isTablet} from './services';
const {width, height} = Dimensions.get('screen');
export default StyleSheet.create({
  mainheader: {
    height: (10 * height) / 100,
    width: width,
    paddingBottom: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  tinyLogo: {
    height: 34,
    width: 34,
    borderRadius: 17,
  },
  mainvdrw: {
    width: '90%',
    height: '93%',
  },
  icondrw: {
    color: '#000',
    alignSelf: 'flex-start',
  },
  rightview: {
    fontSize: fontsizes[11],
    width: isTablet() ? (width * 12) / 100 : (width * 9) / 100,
    height: isTablet() ? (width * 12) / 100 : (width * 9) / 100,
    textAlign: 'center',
    borderRadius: (width * 5) / 100,
    justifyContent: 'center',
    alignItems: 'center',
    color: '#FFFF',
  },
  notifyview: {
    width: 30,
    height: 30,
    backgroundColor: '#FFF',
    borderRadius: 15,
    zIndex: 2,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    alignSelf: 'flex-end',
    top: -10,
    right: -10,
  },
  imageview: {
    width: isTablet() ? 55 : 30,
    height: isTablet() ? 55 : 30,
    backgroundColor: '#ec0334',
    borderRadius: isTablet() ? 29 : 15,
    zIndex: 2,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    alignSelf: 'flex-end',
    top: -10,
    right: -10,
  },
  betweenview: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  textheader: {
    color: '#FFFF',
  },
  iconleftarrow: {
    width: isTablet() ? 55 : 30,
    height: isTablet() ? 55 : 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconarrowback: {
    width: isTablet() ? 55 : 30,
    height: isTablet() ? 55 : 30,
    borderRadius: isTablet() ? 26 : 15,
    backgroundColor: '#21acc8',
    position: 'absolute',
    opacity: 0.5,
    alignSelf: 'center',
  },
  iconarrowbackright: {
    height: isTablet() ? 55 : 30,
    borderRadius: isTablet() ? 27 : 15,
    backgroundColor: '#21acc8',
    position: 'absolute',
    opacity: 0.5,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconL: {
    color: '#FFFF',
    fontSize: fontsizes[6],
    opacity: 2,
    alignSelf: 'center',
  },
  vdrawer: {
    width: '100%',
    marginBottom: 15,
    justifyContent: 'center',
    alignItems: 'center',
    paddingBottom: 100,
    // height: height,
  },
  versins: {
    backgroundColor: '#FFFF',
    width: '100%',
    textAlign: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    paddingBottom: 15,
    alignSelf: 'center',
  },
  viewimgdrw: {
    width: '90%',
    height: '90%',
    alignSelf: 'center',
  },
  imgdrw: {
    width: '100%',
    height: '100%',
  },
  viewdrw: {
    backgroundColor: '#21acc8',
    flexDirection: 'row',
    marginVertical: 5,
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  viewdrw1: {
    backgroundColor: '#FFFF',
    flexDirection: 'row',
    marginVertical: 5,
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 5,
    alignItems: 'center',
    borderColor: 'grey',
    borderWidth: 0.5,
    justifyContent: 'flex-start',
  },
  txtdrw: {
    color: '#000',
    marginHorizontal: 5,
    fontSize: fontsizes[8],
    fontFamily: ffamily,
    textAlign: 'left',
  },
  txtdrw1: {
    color: '#000',
    marginHorizontal: 15,
    fontSize: fontsizes[8],
    fontFamily: ffamily,
    textAlign: 'left',
  },
  txtdrw11: {
    color: 'black',
    marginHorizontal: 15,
    fontSize: fontsizes[8],
    fontFamily: ffamily,
    textAlign: 'left',
  },
  viewtxtdrw: {
    flexDirection: 'row-reverse',
    marginTop: 5,
    marginBottom: 30,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  longform: {
    color: '#000',
    fontSize: fontsizes[8],
    fontFamily: ffamily,
    textAlign: 'left',
  },
  viewfspages: {
    marginBottom: 30,
    borderBottomColor: '#000',
    borderWidth: 1,
    opacity: 0.5,
    width: '95%',
  },
  touchdrw: {
    flexDirection: 'row',
    paddingVertical: 3,
    marginBottom: 15,
    width: '100%',
    // justifyContent: 'space-around',
    alignItems: 'flex-start',
  },
  viewtouchdrw: {
    width: '100%',
    marginBottom: 10,
  },
  imgdrwview: {
    width: 25,
    height: 25,
    marginHorizontal: 15,
  },
  mainheaderview: {
    justifyContent: 'center',
    paddingTop: 10,
    zIndex: 20,
    // backgroundColor:'red',
    alignItems: 'center',
  },
  iconarrowview: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  txtcollect: {
    fontSize: fontsizes[2],
    fontFamily: ffamily,
    textAlign: 'left',
    marginLeft: 10,
    marginTop: 5,
    marginBottom: 5,
  },
  txtcollect5: {
    fontSize: fontsizes[3],
    fontFamily: ffamily,
    textAlign: 'left',
    // marginLeft: 10,
    marginTop: 8,
    // backgroundColor: 'red',
    marginBottom: 0,
  },
  imghead: {
    width: isTablet() ? (width * 20) / 100 : (width * 10) / 100,
    height: isTablet() ? (width * 10) / 100 : (width * 5) / 100,
    padding: 3,
  },
  imgcountby: {
    width: (width * 10) / 100,
    height: (width * 8) / 100,
    padding: 3,
  },
  maintabbtn: {
    backgroundColor: '#FFFF',
    width: '100%',
    height: height * 0.08,
    flexDirection: I18nManager.isRTL ? 'row' : 'row-reverse',
    justifyContent: 'space-around',
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: {
          width: 2,
          height: 2,
        },
        shadowOpacity: 3,
        // shadowRadius: 2.52,
      },
      android: {
        elevation: 2,
      },
    }),
  },
  touchtabbtn: {
    backgroundColor: '#FFFF',
    width: '20%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  txthome: {
    width: '100%',
    height: '100%',
    padding: 15,
  },
  vthome: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  touchsearch: {
    width: '20%',
    justifyContent: 'center',
    alignItems: 'center',
  },
});
